dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: BhSgagGUORRWfu2LtITQgt36oopZQZdOkI71GXw5yvK1t5cxMxg5Mn8kHKREZi9yMtwcL8tURm5hoNA5yXgibXNY0GUcYzqZJzwK3oi2f42uljOG+FVBwJDuISSrImA3+ucPV4swSpp71PwIXE4xqXGd29Y9XKtMTs7x4OPBIc3VxWNzlEuPkIZdIbxYTv2uzKwP1qf/UQxzGrL+lyDYM/gYKDR7DUvVBrN2RL2wUIoSAcXNUvrnDkx0/3mrL8kWtIUS5HQSB8Dsl7fq6uUvWcZqs8Mm1CLMtlLswD1bTlsJ4rpRTdZKqZG21LHS/gRSphgFqUUDisuCb0wbpyVYcra2RvDhe7cAZyJdQQd730Kiwj5tJPS4f/5BxXmz6TYXGrdmKWyohjvOaI3XrXF1HWJ9EORnnfbbSFhVh6wH9NDQhlENP9k5vz0KwhZ7jI83gxMjxuKkNvEevOBjzL+Lb4EGTzQJ8lh/0fpTK9v0KrHFcqAvMzCDM6YyCbAKgIRcqLq0BiBdXOya4qpVgbd2LpmrkD1J5B5REpiVo+DYL0w7DMbQsGVuaNxZMpXTC76tqSDV2yJ10JO94C/HMqRUruz5gLRdzOrhWY5GxRSoRtCPK140hmOwfiQxncw2gKOWHlHNKZMKvKVKUCgwuQ2G2qxFBSl3L0F1mefI8qKrER8=
